map_type: costmap
transform_tolerance: 0.5
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.55

observation_sources: base_scan

max_obstacle_height: 4.0
inscribed_radius: 0.2
circumscribed_radius: 0.3
cost_scaling_factor: 15.0
lethal_cost_threshold: 100


base_scan: {sensor_frame: base_laser_link, 
data_type: LaserScan, 
expected_update_rate: 0.2,
observation_persistance: 0.0, 
marking: true, 
clearing: true}
